name: Compile changelogs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    permissions:
      contents: write # required to push the updated changelog commit
    runs-on: ubuntu-latest
    if: github.repository == 'Proxima-Project/Proxi-Bay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: remastered_new_dev_proxima_2022_gold_edition
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install depends
        run: pip install pyyaml bs4
      - name: Compile CL
        run: python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git diff --quiet --exit-code && echo "No changes found, aborting." && exit 0
          git commit -am "Automatic changelog generation"
          git push
